services:
  - type: web
    name: spirit-api
    env: node
    region: oregon
    plan: starter
    branch: main
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: DASH_ADMIN_TOKEN
        sync: false
      - key: JWT_SECRET
        sync: false
    healthCheckPath: "/"
    autoDeploy: true
    scaling:
      minInstances: 1
      maxInstances: 3
